config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  resources :sections
  resources :checkins
  resources :professors
  resources :students
  get '/prof/:id', to: 'main#prof', as: 'prof'
  get'/stud/:id', to: 'main#stud', as: 'stud'
  get '/post/:student_id/:professor_id/:data' , to:"main#post"
  post '/main/refresh' , to: 'main#refresh'
  get '/main/refresh' , to: 'main#refresh'

  root to: 'main#splash'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/checkin.rb
class Checkin < ApplicationRecord
	belongs_to :student
end

app/controllers/checkins_controller.rb
require 'student'
class BlocksController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.all
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
  end

  # GET /checkins/new
  def new
    @checkin = Checkin.new
  end

  # GET /checkins/1/edit
  def edit
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(checkin_params)
    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render :show, status: :created, location: @checkin }
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkins/1
  # PATCH/PUT /checkins/1.json
  def update
    respond_to do |format|
      if @checkin.update(checkin_params)
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkin }
      else
        format.html { render :edit }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin.destroy
    respond_to do |format|
      format.html { redirect_to checkins_url, notice: 'Checkin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkin_params
      params.require(:checkin).permit(:student_id, :section_id, :time,:status)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= form_with(model: checkin, local: true) do |form| %>
  <% if checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id, id: :checkin_student_id %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.number_field :section_id, id: :checkin_section_id %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time, id: :checkin_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<h1>Editing Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Checkins</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Section</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.student_id %></td>
        <td><%= checkin.section_id %></td>
        <td><%= checkin.time %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New Checkin</h1>

<%= render 'form', checkin: @checkin %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @checkin.student_id %>
</p>

<p>
  <strong>Section:</strong>
  <%= @checkin.section_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @checkin.time %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>